cv/urls.py
from django.urls import re_path
from . import views

app_name='cv'
urlpatterns=[
	 re_path(r'^$', views.IndexView.as_view(),name='index'),
	 re_path(r'^create/$',views.CreateCV,name='create'),
	 re_path(r'^(?P<pk>[0-9]+)/$',views.CView.as_view(),name='detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path,include
from django.contrib import admin

urlpatterns = [
     re_path(r'^admin/', admin.site.urls),
     re_path(r'^',include('cv.urls'))
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

cv/models.py
from django.db import models


def upload(instance,filename):
	return "%s/%s"%(instance.id,filename)

class CV(models.Model):
	name=models.CharField(max_length=50,blank=False)
	phone_no=models.CharField(max_length=15)
	email_id=models.EmailField()
	photo=models.ImageField(upload_to=upload,null=True,height_field='height', width_field='width',blank=True)
	height=models.IntegerField(default=0)
	width=models.IntegerField(default=0)
	about_you=models.TextField()
	address=models.TextField()
	hobbies_and_intrests=models.TextField(blank=True,null=True)
	timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
	profile=models.CharField(max_length=200)
	def __str__(self):
		return self.name
	# skills=models.CharField(max_length=300)
	# education=models.TextField()
	# achievements=models.TextField(,null=True)

class EQ(models.Model):
	cv=models.ForeignKey(CV,on_delete=models.CASCADE,related_name='education')	
	graduation="Graduation"
	senior_secondary="XII Senior Secondary"
	secondary="X Secondary"
	post_graduation="Post Graduation"
	phd="PHD"
	diploma="Diploma"
	courses=(
		(secondary,"Secondary"),
		(senior_secondary,"XII Senior Secondary"),
		(diploma,"Diploma"),
		(graduation,"Graduation"),
		(post_graduation,"Post Graduation"),
		(phd,"PHD")
		)
	course=models.CharField(max_length=30,choices=courses)
	instute_name=models.CharField(max_length=100)
	stream=models.CharField(max_length=50)
	percentage=models.IntegerField()

class Achieve(models.Model):
	cv=models.ForeignKey(CV,on_delete=models.CASCADE,related_name='achievements')
	achievements=models.CharField(max_length=300)

class Skill(models.Model):
	cv=models.ForeignKey(CV,on_delete=models.CASCADE,related_name='skills')
	skill=models.CharField(max_length=30)
	level=models.IntegerField()


class WE(models.Model):
	work_experience=models.ForeignKey(CV,on_delete=models.CASCADE,related_name='work_experience')
	organisation=models.CharField(max_length=50)
	designation=models.CharField(max_length=30)
	location=models.CharField(max_length=30)
	years=models.CharField(max_length=10)

cv/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.forms.models import BaseInlineFormSet
from django.forms import fields, models, formsets, widgets
from .models import CV,EQ,Skill,Achieve,WE

class CVForm(forms.ModelForm):
	class Meta:
		model=CV
		fields =['name','phone_no','email_id','profile','about_you','photo','address','hobbies_and_intrests']
		widgets={
		'name':forms.TextInput(attrs={'placeholder':'Enter your Full Name here'}),
		'phone_no':forms.TextInput(attrs={'placeholder':'Enter your Phone No here'}),
		'email_id':forms.TextInput(attrs={'placeholder':'Enter your email id here'}),
		'hobbies_and_intrests':forms.Textarea(attrs={'placeholder':'Enter your hobbies here'}),
		}
class EQForm(forms.ModelForm):
	class Meta:
		model=EQ
		fields=['course','instute_name','stream','percentage']
		widgets={
		'course':forms.Select(attrs={'class':'form-control'}),
		'instute_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter name of institution here'}),
		'stream':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your Stream'}),
		'percentage':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your percentages here'}),
		}
class SkillForm(forms.ModelForm):
	class Meta:
		model=Skill
		fields=['skill','level']
		widgets={
		'skill':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter skill'}),
		'level':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your level in percentage'}),
		}

class AchievementForm(forms.ModelForm):
	class Meta:
		model=Achieve
		fields=['achievements']
		widgets={
		'achievements':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter your achievement'}),
		}

class WEForm(forms.ModelForm):
	class Meta:
		model=WE
		fields =['organisation','designation','location','years']
		widgets={
		'organisation':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter organisation Name here'}),
		'designation':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter designation here'}),
		'location':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter location of company here'}),
		'years':forms.TextInput(attrs={'class':'form-control','placeholder':'years of experience there'}),
		}


def get_eq_formset(form, formset=models.BaseInlineFormSet, **kwargs):
	return models.inlineformset_factory(CV, EQ, form, formset, **kwargs)

def get_skill_formset(form, formset=models.BaseInlineFormSet, **kwargs):
	return models.inlineformset_factory(CV, Skill, form, formset, **kwargs)

def get_achieve_formset(form, formset=models.BaseInlineFormSet, **kwargs):
	return models.inlineformset_factory(CV, Achieve, form, formset, **kwargs)

def get_we_formset(form, formset=models.BaseInlineFormSet, **kwargs):
	return models.inlineformset_factory(CV, WE, form, formset, **kwargs)

cv/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView
from .models import *
from django.urls import reverse
from .forms import *


class IndexView(ListView):
    template_name='cv/index.html'
    context_object_name='cv_list'

    def get_queryset(self):
        return CV.objects.all()


class CView(DetailView):
    model = CV
    template_name = 'cv/resume.html'


def CreateCV(request):
    EQFormSet = get_eq_formset(EQForm, extra=1, can_delete=True)
    SKILLSFormSet = get_skill_formset(SkillForm, extra=1, can_delete=True)
    ACHIEVEFormSet = get_achieve_formset(AchievementForm, extra=1, can_delete=True)
    WEFormSet = get_we_formset(WEForm, extra=1, can_delete=True)
    if request.POST:
        form = CVForm(request.POST or None, request.FILES or None)
        print (form.is_valid())
        if form.is_valid():
            cv = form.save(commit=False)
            eqformset = EQFormSet(request.POST or None, request.FILES or None, prefix='education_form', instance=cv)
            skillformset = SKILLSFormSet(request.POST or None, request.FILES or None, prefix='skills_form', instance=cv)
            achieveformset = ACHIEVEFormSet(request.POST or None, request.FILES or None, prefix='achievement_form', instance=cv)
            weformset = WEFormSet(request.POST or None, request.FILES or None, prefix='work_experience_form',instance=cv)

            if eqformset.is_valid() and skillformset.is_valid() and achieveformset.is_valid() and weformset.is_valid():
                cv.save()
                eqformset.save()
                skillformset.save()
                achieveformset.save()
                weformset.save()
                return redirect('cv:detail', pk=cv.id)
        else:
            return render(request, 'cv/error.html', {'form':form})
    else:
        form = CVForm()
        eqformset = EQFormSet(prefix='education_form', instance=CV())
        skillformset = SKILLSFormSet(prefix='skills_form', instance=CV())
        achieveformset = ACHIEVEFormSet(prefix='achievement_form', instance=CV())
        weformset = WEFormSet(prefix='work_experience_form', instance=CV())
    context={
            'form': form,
            'eqformset': eqformset,
            'skillformset': skillformset,
            'achieveformset': achieveformset,
            'weformset': weformset

        }
    return render(request, 'cv/create.html', context)

cv/templates/cv/create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet' type='text/css'>
	<link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/css/bootstrap-switch.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-imageupload.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
</head>
<body>
	<style>
.panel-default {
     border:none !important; 
}

.form-horizontal .control-label {
     text-align:left; 
}
body{
	margin-top: 50px;
}
.panel-primary{
    border:none;
}
	</style>
	<div class='container'>
		<div class='panel panel-primary dialog-panel'>
      		<div class='panel-heading'>
        		<h5>Create your CV - Here</h5>
      		</div>
      		<div class='panel-body' style="box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;">
				<form class="form-horizontal" action=" "action="" role="form" method="post" enctype="multipart/form-data">
					<legend>Personal Information</legend>
				{% csrf_token %}
					<div class='form-group'>
            			<label class='control-label col-md-2 col-md-offset-2'>Full Name</label>
            			<div class='col-md-6'>
              				<div class='form-group'>
                				<div class='col-md-11'>
                  					<input class='form-control' name='{{form.name.name}}' placeholder='Enter Your Name Here'>
                				</div>
              				</div>
          				</div>
          			</div>
          			<div class='form-group'>
            			<label class='control-label col-md-2 col-md-offset-2'>Profile</label>
            			<div class='col-md-6'>
              				<div class='form-group'>
                				<div class='col-md-11'>
                  					<input class='form-control' name='{{form.profile.name}}' placeholder='Enter Your Profile Here'>
                				</div>
              				</div>
          				</div>
          			</div>
          			<div class='form-group'>
		            	<label class='control-label col-md-2 col-md-offset-2'>Phone No</label>
		            	<div class='col-md-6'>
		              		<div class='form-group'>
		                		<div class='col-md-11'>
		                  			<input class='form-control' name='{{form.phone_no.name}}' placeholder='Enter Phone No Here'>
	                			</div>
	              			</div>
	          			</div>
          			</div>
          		<div class='form-group'>
		            <label class='control-label col-md-2 col-md-offset-2'>Email Id</label>
		            <div class='col-md-6'>
		              <div class='form-group'>
		                <div class='col-md-11'>
		                  <input class='form-control' name='{{form.email_id.name}}' placeholder='Enter Your Name Here'>
		                </div>
		              </div>
		          	</div>
		        </div>
          		<div class='form-group'>
		            <label class='control-label col-md-2 col-md-offset-2'>Upload Image</label>
		            <div class='col-md-6'>
		            	<div class='form-group'>
		                    <div class="imageupload panel panel-default" style="padding-top:20px">
		                		<div class="file-tab panel-body">
		                    		<label class="btn btn-default btn-file">
		                        		<span>Browse</span><!-- The file is stored here. -->
		                        		<input type="file" name="{{form.photo.name}}">
		                    		</label>
		                    		<button type="button" class="btn btn-default">Remove</button>
		                		</div>
			        		</div>
	    				</div>
	        		</div>
			    </div>
			    <div class='form-group'>
            		<label class='control-label col-md-2 col-md-offset-2' >Address</label>
            		<div class='col-md-6'>
              			<textarea class='form-control' name="{{form.address.name}}" placeholder='Enter your address' rows='3'></textarea>
            		</div>
          		</div>
          		<div class='form-group'>
            		<label class='control-label col-md-2 col-md-offset-2' >Hobbies & Intrests</label>
            		<div class='col-md-6'>
              			<textarea class='form-control' name="{{form.hobbies_and_intrests.name}}" placeholder='Tell us something more about you' rows='3'></textarea>
            		</div>
          		</div>
          		<div class='form-group'>
            		<label class='control-label col-md-2 col-md-offset-2' >What I am all about</label>
            		<div class='col-md-6'>
              			<textarea class='form-control' name="{{form.about_you.name}}" placeholder='What I am all about' rows='3'></textarea>
            		</div>
          		</div>
		
		
			
				<legend>Educational Qualifications</legend>
				<div class="form-group">
				{{ eqformset.management_form }}
				{{ eqformset.non_form_errors }}
				{% for form in eqformset %}
					{{ form.id }}
					<div class="inline {{ eqformset.prefix }}">
						{{ form.course.errors }}
						<label class='control-label col-md-2' >{{ form.course.label_tag }}</label>
						<div class='form-group internal col-md-4'>
						{{form.course}}
						</div>
						{{ form.instute_name.errors }}
						<label class='control-label col-md-2' >{{ form.instute_name.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.instute_name }}
						</div>
						{{ form.stream.errors }}
						<label class='control-label col-md-2' >{{ form.stream.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.stream }}
						</div>
						{{ form.percentage.errors }}
						<label class='control-label col-md-2' >{{ form.percentage.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.percentage }}
						</div>
					</div>
				{% endfor %}
				</div>
			<fieldset>
				<legend>Skills</legend>
				<div class="form-group">
				{{ skillformset.management_form }}
				{{ skillformset.non_form_errors }}
				{% for form in skillformset %}
					{{ form.id }}
					<div class="inline {{ skillformset.prefix }}">
						
						<label class='control-label col-md-2' >{{ form.skill.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.skill.errors }}
							{{ form.skill }}
							
						</div>
						
						<label class='control-label col-md-2' >{{ form.level.label_tag }}</label>
						<div class='form-group internal col-md-4'>
						{{ form.level.errors }}
						{{ form.level }}
						</div>
						
						
					</div>
				{% endfor %}
				</div>
			</fieldset>
			<fieldset>
				<legend>Achievements</legend>
				{{  achieveformset.management_form }}
				{{ achieveformset.non_form_errors }}
				{% for form in achieveformset %}
					{{ form.id }}
					<div class="inline {{ achieveformset.prefix }}">
						{{ form.achievements.errors }}
						<label class='control-label col-md-2 col-md-offset-2' >{{ form.achievements.label_tag }}</label>
						<div class='form-group internal col-md-6'>
							{{ form.achievements }}
						</div>
					</div>
				{% endfor %}
			</fieldset>
			<fieldset>
				<legend>Work Experience</legend>
				{{  weformset.management_form }}
				{{ weformset.non_form_errors }}
				{% for form in weformset %}
					{{ form.id }}
					<div class="inline {{ weformset.prefix }}">
						{{ form.organisation.errors }}
						<label class='control-label col-md-2' >{{ form.organisation.label_tag }}</label>
						<div class='form-group internal col-md-4'>
						{{form.organisation}}
						</div>
						{{ form.designation.errors }}
						<label class='control-label col-md-2' >{{ form.designation.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.designation }}
						</div>
						{{ form.location.errors }}
						<label class='control-label col-md-2' >{{ form.location.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.location }}
						</div>
						{{ form.years.errors }}
						<label class='control-label col-md-2' >{{ form.years.label_tag }}</label>
						<div class='form-group internal col-md-4'>
							{{ form.years }}
						</div>
					</div>
					{% endfor %}
			</fieldset>
			<div class='form-group'>
            <div class='col-md-offset-6 col-md-4'>
              <button class='btn-lg btn-primary' type='submit'>Submit</button>
            </div>
        	</div>
	<!-- <input type="submit" value="Submit" class="submit" /> -->
	</form>
	</div>
</div>
    	</div>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script  type="text/javascript" src="{% static 'js/jquery.formset.js' %}"></script>
	<script type="text/javascript">
		$(function() {
		$(".inline.{{ eqformset.prefix }}").formset({
		prefix: "{{ eqformset.prefix }}",
		})
		$(".inline.{{ skillformset.prefix }}").formset({
		prefix: "{{ skillformset.prefix }}",
		})
		$(".inline.{{ achieveformset.prefix }}").formset({
		prefix: "{{ archieveformset.prefix }}",
		})
		$(".inline.{{ weformset.prefix }}").formset({
		prefix: "{{ weformset.prefix }}",
		})
	})
</script>
	<script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.0/js/bootstrap.min.js'></script>
	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/js/bootstrap-switch.min.js"></script>
	<script src="{% static 'js/bootstrap-imageupload.js' %}"></script>
	<script>
        var $imageupload = $('.imageupload');
        $imageupload.imageupload();
    </script>

</body>
</html>

cv/templates/cv/error.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        {{field.name}}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

cv/templates/cv/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet' type='text/css'>
	<link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.8/css/bootstrap-switch.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-imageupload.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
</head>
<body>
	<div class="container">
		{% if cv_list %}
		<div class="header">
			<div class="row list-group">
				<div class="col-md-4 list-group-item list-group-item-action">
					<h2>Created BY</h2>
				</div>
				<div class="col-md-4 list-group-item list-group-item-action">
					<h2>Created On</h2>
				</div>
				<div class="col-md-4 list-group-item list-group-item-action">
					<h2>Action</h2>
				</div>
			</div>
		</div>
		<section>
			
			{% for cv in cv_list %}
			<div class="row list-group ">
				<div class="col-md-4 list-group-item list-group-item-action">
					<p >{{ cv.name }}</p>
				</div>
				<div class="col-md-4 list-group-item list-group-item-action">
					<p >{{ cv.timestamp }}</p>
				</div>
				<div class="col-md-4 list-group-item list-group-item-action">
					<p><a href="{% url 'cv:detail' cv.id %}" >View</a></p>
				</div>
			</div>
			{% endfor %}
			<p class="list-group-item list-group-item-action">Create Your Resume? <a href="{% url 'cv:create' %}">click here</p>
			{% else %}
				<h1 class="text-center list-group-item list-group-item-action"> No resumes </h1>
				<p class="list-group-item list-group-item-action">Create Your Resume? <a href="{% url 'cv:create' %}">click here</p>
			
		</section>
		{% endif %}
	</div>


	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>















	

cv/templates/cv/resume.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{ title }}</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open Sans' rel='stylesheet' type='text/css'>
	<link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar">
	<div id="main-wrapper">
		<!-- Page Preloader -->
		<div id="preloader">
		    <div id="status">
		        <div class="status-mes"></div>
		    </div>
		</div>
		

		<div class="columns-block">
			<div class="left-col-block blocks">
			    <header class="header">
			        <div class="content text-center">
			            <h1>Hi, I'm {{ cv.name }}!</h1>

			            <p class="lead">{{ cv.profile }}</p>
			     
			        </div>
			        <div class="profile-img">
			        	{% if cv.photo %}
						<img src="{{ cv.photo.url }}" style="height: inherit;width: inherit;">
						{% endif %}
					</div>
			    </header>
			    <!-- .header-->
			</div>
			<div class="right-col-block blocks">
				<section class="intro section-wrapper">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title">
				                    <h2>What I am all about.</h2>
				                </div>
				            </div>
				            <div class="col-md-12">
				                <p>
				                    {{ cv.about_you }}
				                </p>
				            </div>
				        </div>
				    </div>
				</section>
				<section class="section-wrapper skills-wrapper gray-bg">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title">
				                    <h2>Skills</h2>
				                </div>
				            </div>
				        </div>
				        <!--.row-->
				        <div class="row">
				            <div class="col-md-12">
				                <div class="progress-wrapper">
				                	{% for i in cv.skills.all %}
										
				                    <div class="progress-item">
				                        <span class="progress-title">{{i.skill}}</span>

				                        <div class="progress">
				                            <div class="progress-bar" role="progressbar" aria-valuenow="{{i.level}}" aria-valuemin="0"
				                                 aria-valuemax="100" style="width:{{i.level}}%"><span class="progress-percent"> {{i.level}}%</span>
				                            </div>
				                        </div>
				                        <!-- .progress -->
				                    </div>
				                    <!-- .skill-progress -->

				                    {% endfor %}
				                </div>
				                <!-- /.progress-wrapper -->
				            </div>
				        </div>
				        <!--.row -->
				    </div>
				    <!-- .container-fluid -->
				</section>
				<!-- .skills-wrapper -->
				<section class="section-wrapper section-experience ">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title"><h2>Work Experience</h2></div>
				            </div>
				        </div>
				        <!--.row-->
				        <div class="row">
				            <div class="col-md-12">
				            	{% for i in cv.work_experience.all %}
				                <div class="content-item">
				                    <small>{{i.years}}</small>
				                    <h3>{{i.designation}}</h3>
				                    <h4>{{i.organisation}}</h4>

				                    <p>{{i.location}}</p>
				                </div>
				                <!-- .experience-item -->
				                {% endfor %}
				            </div>
				        </div>
				        <!--.row-->
				    </div>
				    <!-- .container-fluid -->

				</section>
				<!-- .section-experience -->
				<section class="section-wrapper section-education gray-bg">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title"><h2>Education</h2></div>
				            </div>
				        </div>
				        <!--.row-->
				        <div class="row">
				            <div class="col-md-12">
				            	{% for i in cv.education.all %}
				                <div class="content-item">
				                    <small>{{ i.percentage }}%</small>
				                    <h3>{{ i.course }}</h3>
				                    <h4>{{ i.stream }}</h4>

				                    <p>{{ i.instute_name }}</p>
				                </div>
				                <!-- .experience-item -->
				                {% endfor %}
				            </div>
				        </div>
				        <!--.row-->
				    </div>
				    <!-- .container-fluid -->

				</section>
				<!-- .section-education -->
				<section class="section-wrapper section-interest ">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title">
				                    <h2>Interest</h2>
				                </div>
				            </div>
				        </div>
				        <!-- .row -->

				        <div class="row">
				            <div class="col-md-12">
				                <div class="col-md-12">
				                <p>
				                    {{cv.hobbies_and_intrests}}
				                </p>
				            	</div>
				                
				            </div>
				        </div>
				        <!-- .row -->

				    </div>
				</section>

				<section class="section-contact section-wrapper gray-bg">
				    <div class="container-fluid">
				        <div class="row">
				            <div class="col-md-12">
				                <div class="section-title">
				                    <h2>Contact</h2>
				                </div>
				            </div>
				        </div>
				        <!--.row-->
				        <div class="row">
				            <div class="col-md-12">
				            	<address>
				                    <strong>Address</strong><br>
				                    {{ cv.address }}
				                </address>
				                <address>
				                    <strong>Mobile Number</strong><br>
				                    {{ cv.phone_no }}
				                </address>
				                <address>
				                    <strong>Email</strong><br>
				                 	{{ cv.email_id }}
				                </address>
				            </div>
				        </div>
				    </div>
				</section>




			</div>

		</div>
	</div>




<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

	
</body>
</html>